// Code generated by xgen. DO NOT EDIT.

package main

// Iso8583PostXml ...
type Iso8583PostXml struct {
	MsgType string  `xml:"MsgType"`
	Fields  *Fields `xml:"Fields"`
}

// MsgType ...
type MsgType string

// Fields ...
type Fields struct {
	Field002    string   `xml:"Field_002"`
	Field003    string   `xml:"Field_003"`
	Field004    string   `xml:"Field_004"`
	Field005    string   `xml:"Field_005"`
	Field007    string   `xml:"Field_007"`
	Field009    string   `xml:"Field_009"`
	Field011    string   `xml:"Field_011"`
	Field012    string   `xml:"Field_012"`
	Field013    string   `xml:"Field_013"`
	Field014    string   `xml:"Field_014"`
	Field015    string   `xml:"Field_015"`
	Field016    string   `xml:"Field_016"`
	Field018    string   `xml:"Field_018"`
	Field022    string   `xml:"Field_022"`
	Field023    string   `xml:"Field_023"`
	Field025    string   `xml:"Field_025"`
	Field026    string   `xml:"Field_026"`
	Field027    string   `xml:"Field_027"`
	Field028    string   `xml:"Field_028"`
	Field029    string   `xml:"Field_029"`
	Field030    string   `xml:"Field_030"`
	Field031    string   `xml:"Field_031"`
	Field032    string   `xml:"Field_032"`
	Field033    string   `xml:"Field_033"`
	Field035    string   `xml:"Field_035"`
	Field037    string   `xml:"Field_037"`
	Field038    string   `xml:"Field_038"`
	Field039    string   `xml:"Field_039"`
	Field040    string   `xml:"Field_040"`
	Field041    string   `xml:"Field_041"`
	Field042    string   `xml:"Field_042"`
	Field043    string   `xml:"Field_043"`
	Field044    string   `xml:"Field_044"`
	Field045    string   `xml:"Field_045"`
	Field048    string   `xml:"Field_048"`
	Field049    string   `xml:"Field_049"`
	Field050    string   `xml:"Field_050"`
	Field052    string   `xml:"Field_052"`
	Field053    string   `xml:"Field_053"`
	Field054    string   `xml:"Field_054"`
	Field056    string   `xml:"Field_056"`
	Field057    string   `xml:"Field_057"`
	Field058    string   `xml:"Field_058"`
	Field059    string   `xml:"Field_059"`
	Field066    string   `xml:"Field_066"`
	Field067    string   `xml:"Field_067"`
	Field070    string   `xml:"Field_070"`
	Field073    string   `xml:"Field_073"`
	Field074    string   `xml:"Field_074"`
	Field075    string   `xml:"Field_075"`
	Field076    string   `xml:"Field_076"`
	Field077    string   `xml:"Field_077"`
	Field078    string   `xml:"Field_078"`
	Field079    string   `xml:"Field_079"`
	Field080    string   `xml:"Field_080"`
	Field081    string   `xml:"Field_081"`
	Field082    string   `xml:"Field_082"`
	Field083    string   `xml:"Field_083"`
	Field084    string   `xml:"Field_084"`
	Field085    string   `xml:"Field_085"`
	Field086    string   `xml:"Field_086"`
	Field087    string   `xml:"Field_087"`
	Field088    string   `xml:"Field_088"`
	Field089    string   `xml:"Field_089"`
	Field090    string   `xml:"Field_090"`
	Field091    string   `xml:"Field_091"`
	Field095    string   `xml:"Field_095"`
	Field097    string   `xml:"Field_097"`
	Field098    string   `xml:"Field_098"`
	Field100    string   `xml:"Field_100"`
	Field101    string   `xml:"Field_101"`
	Field102    string   `xml:"Field_102"`
	Field103    string   `xml:"Field_103"`
	Field118    string   `xml:"Field_118"`
	Field119    string   `xml:"Field_119"`
	Field123    string   `xml:"Field_123"`
	Field125    string   `xml:"Field_125"`
	Field127002 string   `xml:"Field_127_002"`
	Field127003 string   `xml:"Field_127_003"`
	Field127004 string   `xml:"Field_127_004"`
	Field127005 string   `xml:"Field_127_005"`
	Field127006 string   `xml:"Field_127_006"`
	Field127007 string   `xml:"Field_127_007"`
	Field127008 string   `xml:"Field_127_008"`
	Field127009 string   `xml:"Field_127_009"`
	Field127010 string   `xml:"Field_127_010"`
	Field127011 string   `xml:"Field_127_011"`
	Field127012 string   `xml:"Field_127_012"`
	Field127013 string   `xml:"Field_127_013"`
	Field127014 string   `xml:"Field_127_014"`
	Field127015 string   `xml:"Field_127_015"`
	Field127016 string   `xml:"Field_127_016"`
	Field127017 string   `xml:"Field_127_017"`
	Field127018 string   `xml:"Field_127_018"`
	Field127019 string   `xml:"Field_127_019"`
	Field127020 string   `xml:"Field_127_020"`
	Field127021 string   `xml:"Field_127_021"`
	Field127022 string   `xml:"Field_127_022"`
	Field127023 string   `xml:"Field_127_023"`
	Field127024 string   `xml:"Field_127_024"`
	Field127025 *IccData `xml:"Field_127_025"`
	Field127026 string   `xml:"Field_127_026"`
	Field127027 string   `xml:"Field_127_027"`
	Field127028 string   `xml:"Field_127_028"`
	Field127029 string   `xml:"Field_127_029"`
	Field127030 string   `xml:"Field_127_030"`
	Field127031 string   `xml:"Field_127_031"`
	Field127032 string   `xml:"Field_127_032"`
	Field127033 string   `xml:"Field_127_033"`
	Field127034 string   `xml:"Field_127_034"`
	Field127035 string   `xml:"Field_127_035"`
}

// Field002 ...
type Field002 string

// Field003 ...
type Field003 string

// Field004 ...
type Field004 string

// Field005 ...
type Field005 string

// Field007 ...
type Field007 string

// Field009 ...
type Field009 string

// Field011 ...
type Field011 string

// Field012 ...
type Field012 string

// Field013 ...
type Field013 string

// Field014 ...
type Field014 string

// Field015 ...
type Field015 string

// Field016 ...
type Field016 string

// Field018 ...
type Field018 string

// Field022 ...
type Field022 string

// Field023 ...
type Field023 string

// Field025 ...
type Field025 string

// Field026 ...
type Field026 string

// Field027 ...
type Field027 string

// Field028 ...
type Field028 string

// Field029 ...
type Field029 string

// Field030 ...
type Field030 string

// Field031 ...
type Field031 string

// Field032 ...
type Field032 string

// Field033 ...
type Field033 string

// Field035 ...
type Field035 string

// Field037 ...
type Field037 string

// Field038 ...
type Field038 string

// Field039 ...
type Field039 string

// Field040 ...
type Field040 string

// Field041 ...
type Field041 string

// Field042 ...
type Field042 string

// Field043 ...
type Field043 string

// Field044 ...
type Field044 string

// Field045 ...
type Field045 string

// Field048 ...
type Field048 string

// Field049 ...
type Field049 string

// Field050 ...
type Field050 string

// Field052 ...
type Field052 string

// Field053 ...
type Field053 string

// Field054 ...
type Field054 string

// Field056 ...
type Field056 string

// Field057 ...
type Field057 string

// Field058 ...
type Field058 string

// Field059 ...
type Field059 string

// Field066 ...
type Field066 string

// Field067 ...
type Field067 string

// Field070 ...
type Field070 string

// Field073 ...
type Field073 string

// Field074 ...
type Field074 string

// Field075 ...
type Field075 string

// Field076 ...
type Field076 string

// Field077 ...
type Field077 string

// Field078 ...
type Field078 string

// Field079 ...
type Field079 string

// Field080 ...
type Field080 string

// Field081 ...
type Field081 string

// Field082 ...
type Field082 string

// Field083 ...
type Field083 string

// Field084 ...
type Field084 string

// Field085 ...
type Field085 string

// Field086 ...
type Field086 string

// Field087 ...
type Field087 string

// Field088 ...
type Field088 string

// Field089 ...
type Field089 string

// Field090 ...
type Field090 string

// Field091 ...
type Field091 string

// Field095 ...
type Field095 string

// Field097 ...
type Field097 string

// Field098 ...
type Field098 string

// Field100 ...
type Field100 string

// Field101 ...
type Field101 string

// Field102 ...
type Field102 string

// Field103 ...
type Field103 string

// Field118 ...
type Field118 string

// Field119 ...
type Field119 string

// Field123 ...
type Field123 string

// Field125 ...
type Field125 string

// Field127002 ...
type Field127002 string

// Field127003 ...
type Field127003 string

// Field127004 ...
type Field127004 string

// Field127005 ...
type Field127005 string

// Field127006 ...
type Field127006 string

// Field127007 ...
type Field127007 string

// Field127008 ...
type Field127008 string

// Field127009 ...
type Field127009 string

// Field127010 ...
type Field127010 string

// Field127011 ...
type Field127011 string

// Field127012 ...
type Field127012 string

// Field127013 ...
type Field127013 string

// Field127014 ...
type Field127014 string

// Field127015 ...
type Field127015 string

// Field127016 ...
type Field127016 string

// Field127017 ...
type Field127017 string

// Field127018 ...
type Field127018 string

// Field127019 ...
type Field127019 string

// Field127020 ...
type Field127020 string

// Field127021 ...
type Field127021 string

// Field127022 ...
type Field127022 string

// Field127023 ...
type Field127023 string

// Field127024 ...
type Field127024 string

// Field127025 ...
type Field127025 *IccData

// Field127026 ...
type Field127026 string

// Field127027 ...
type Field127027 string

// Field127028 ...
type Field127028 string

// Field127029 ...
type Field127029 string

// Field127030 ...
type Field127030 string

// Field127031 ...
type Field127031 string

// Field127032 ...
type Field127032 string

// Field127033 ...
type Field127033 string

// Field127034 ...
type Field127034 string

// Field127035 ...
type Field127035 string

// IccData ...
type IccData struct {
	IccRequest *IccRequestType `xml:"IccRequest"`
}

// IccRequestType ...
type IccRequestType struct {
	AmountAuthorized              string `xml:"AmountAuthorized"`
	AmountOther                   string `xml:"AmountOther"`
	ApplicationInterchangeProfile string `xml:"ApplicationInterchangeProfile"`
	ApplicationTransactionCounter string `xml:"ApplicationTransactionCounter"`
	Cryptogram                    string `xml:"Cryptogram"`
	CryptogramInformationData     string `xml:"CryptogramInformationData"`
	CvmResults                    string `xml:"CvmResults"`
	IssuerApplicationData         string `xml:"IssuerApplicationData"`
	TerminalCapabilities          string `xml:"TerminalCapabilities"`
	TerminalCountryCode           string `xml:"TerminalCountryCode"`
	TerminalType                  string `xml:"TerminalType"`
	TerminalVerificationResult    string `xml:"TerminalVerificationResult"`
	TransactionCurrencyCode       string `xml:"TransactionCurrencyCode"`
	TransactionDate               string `xml:"TransactionDate"`
	TransactionType               string `xml:"TransactionType"`
	UnpredictableNumber           string `xml:"UnpredictableNumber"`
}
