// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTunnel() {
  return window['go']['main']['App']['CloseTunnel']();
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function PingTunnel() {
  return window['go']['main']['App']['PingTunnel']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendReversalMessage(arg1) {
  return window['go']['main']['App']['SendReversalMessage'](arg1);
}

export function UpdateConfigs(arg1) {
  return window['go']['main']['App']['UpdateConfigs'](arg1);
}

export function UseTunnel() {
  return window['go']['main']['App']['UseTunnel']();
}
